### PR TITLE
Signup login components

### PR DESCRIPTION
**Pull request by akhildhiman**
We are done with front-end setup @Yjspoder @AmanSharma4419  please review.

### CODE REVIEW

**Comment by yashjk** [comment]
Approved

**Comment by AmanSharma4419** [comment]
Approved

**Comment by prank7** [comment]
File organization is not good. Organize React components by feature. Say "Auth" folder should have all the files related to signup/login. 

Also, each page should be on different routes.
/signup -> For signup
/login -> For login

@BadBrahmin @akhildhiman please fix this.

**Review by prank7 — CHANGES_REQUESTED** [review]
Please see the comment. Need changes in file structure.

**Comment by akhildhiman** [comment]
I've updated folder structure and routing. Please review this **@Yjspoder and @AmanSharma4419**.

**Pull request merged**
